version: "3"
services:
  api:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:4
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
    driver: local
